[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[rpc_endpoints]
scroll_sepolia = "${ETH_RPC_URL}"

[etherscan]
scroll_sepolia = { key = "${ETHERSCAN_API_KEY}"}

